ekyna_advertisement_example_index:
    path: ""
    defaults: { _controller: EkynaAdvertisementBundle:Example:index }
    methods: [GET]

ekyna_advertisement_example_submit:
    path: /submit
    defaults: { _controller: EkynaAdvertisementBundle:Example:submit }
    methods: [GET, POST]
    options:
        expose: true

ekyna_advertisement_example_detail:
    path: /{slug}
    defaults: { _controller: EkynaAdvertisementBundle:Example:detail }
    methods: [GET]
    requirements:
        slug: "[a-zA-Z0-9-]+"
